#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
if (file_exists(__DIR__.'/installed.json')) {
    $app = require_once __DIR__.'/bootstrap/app.php';
} else {
    $app = require_once __DIR__.'/bootstrap/uninstalled.php';
}

$status = $app->handleCommand(new ArgvInput);

exit($status);
